### PR TITLE
Update winapi and bump version

### PR DESCRIPTION
**Pull request by Eijebong**
I also removed a warning because of some deprecated imports that's been on stable for quite some time now.
I took the liberty of bumping the version as the crate seems pretty unmaintained but is used in the wild and duping quite a few (big) dependencies such as regex and winapi and it would be greate to get a new release out :)

### CODE REVIEW

**Comment by jan-hudec** [comment]
> I took the liberty of bumping the version

.. which breaks the release process, so...

**Comment by jan-hudec** [comment]
The rest *will* be accepted though. Thanks for the bump.

**Comment by Eijebong** [comment]
Sure. Maybe next time just ask for the person to remove the commit though ? :p

**Comment by jan-hudec** [comment]
If I knew you are watching this closely I would, because GitHub is pretty bad as far as getting to the content of the merge-requests, but I didn't want to assume you are.

**Comment by jan-hudec** [comment]
And I need to do things manually to retry the Travis build anyway. Because the failure is probably unrelated—and pretty cryptic—but I want to check it.

**Pull request closed without merging**
